### ISSUE TITLE
geoip

### ISSUE THREAD

**Issue by t94j0** [t94j0/satellite#16]
Create conditional for GeoIP

index.html.info
```yaml
geoip:
  authorized_countries: US
  blacklist_countries: EU
```

https://github.com/oschwald/geoip2-golang
