### ISSUE TITLE
Issues with *.info file rules being applied in latest source build

### ISSUE THREAD

**Issue by shogunlab** [t94j0/satellite#34]
Hi there! I'm currently trying to use a source build of satellite and got the server running successfully. 

However, when I write a rule for authorized user agents in an index.html.info file, I can still access the index.html file from the server with a user agent that should not be allowed. Other rules such as "serve" do not appear to be applied successfully either. 

Is this something you're seeing with the current source build as well? Just wanted to flag it if it's an issue on your end too. If not, no worries, feel free to close the ticket and I can continue troubleshooting on my own. 

This is my current config, if you see that your rules are being properly applied, I'd be interested to see your config files if possible so I can try replicating your setup.

/etc/satellite/config.yml:
```
server_root: /var/www/html
listen: :443
index: /index.html
log_level: debug

server_header: Apache/2.4.1 (Unix)

geoip_path: /var/lib/satellite/GeoLite2-Country.mmdb

ssl:
  key: /etc/satellite/keys/key.pem
  cert: /etc/satellite/keys/cert.pem
```

/var/www/html/index.html:
```
<h1>It worked!</h1>
```

/var/www/html/index.html.info:
```
authorized_useragents:
- Test123
```

If you'd like to see any other file contents or configs to troubleshoot, just let me know and I can provide them. Thanks for publishing this project and all your work on it! I think it's really interesting and valuable for the community. Cheers.

**Comment by shogunlab** [comment]
Also, here's the output after running satellite:
```
DEBU[0000] Using config file /etc/satellite/config.yml
DEBU[0000] Using server path /var/www/html
DEBU[0000] Loaded 0 path(s)
WARN[0000] Use not_found handlers for opsec
INFO[0000] Listening HTTPS on port :443
```

I think the issue might be due to the loading of paths since it says "Loaded 0 path(s)" in the output, but that's just a guess on my part.

**Comment by t94j0** [comment]
Hey! Thanks for the kind words.

Just for a test, try using pathList.yml instead of a *.info file.

/var/www/html/pathList.yml
```yml
- path: /index.html
  authorized_useragents:
    - Test123
```

Let me know if that works. There may be something wrong with the .info collection mechanism
